apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shopping-app.name" . }}
  namespace: {{ include "shopping-app.namespace" . }}
  labels:
    {{- include "shopping-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {app.kubernetes.io/name: {{ include "shopping-app.name" . }}, app.kubernetes.io/instance: {{ .Release.Name }}}
  strategy: {type: RollingUpdate, rollingUpdate: {maxSurge: 1, maxUnavailable: 0}}
  template:
    metadata:
      labels: {app.kubernetes.io/name: {{ include "shopping-app.name" . }}, app.kubernetes.io/instance: {{ .Release.Name }}, app.kubernetes.io/part-of: shopping-cart, pci-scope: "true"}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap/payment-service-config.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "shopping-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{name: http, containerPort: {{ .Values.containerPort }}, protocol: TCP}]
          envFrom:
            - configMapRef: {name: {{ include "shopping-app.name" . }}-config}
            - secretRef: {name: {{ .Values.externalSecret.targetName }}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          startupProbe:
            httpGet: {path: {{ .Values.probes.startup.path }}, port: http}
            {{- omit .Values.probes.startup "path" | toYaml | nindent 12 }}
          livenessProbe:
            httpGet: {path: {{ .Values.probes.liveness.path }}, port: http}
            {{- omit .Values.probes.liveness "path" | toYaml | nindent 12 }}
          readinessProbe:
            httpGet: {path: {{ .Values.probes.readiness.path }}, port: http}
            {{- omit .Values.probes.readiness "path" | toYaml | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.extraVolumes | nindent 8 }}

