apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopping-app.name" . }}
  namespace: {{ include "shopping-app.namespace" . }}
  labels:
    {{- include "shopping-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: [{name: {{ .Values.service.portName }}, port: {{ .Values.service.port }}, targetPort: {{ .Values.service.targetPort }}, protocol: TCP}]
  selector: {app.kubernetes.io/name: {{ include "shopping-app.name" . }}, app.kubernetes.io/instance: {{ .Release.Name }}}

