{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: {name: {{ include "account.name" . }}, namespace: {{ include "account.namespace" . }}}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef: {name: {{ .Values.externalSecret.storeName }}, kind: {{ .Values.externalSecret.storeKind }}}
  target: {name: {{ .Values.externalSecret.targetName }}, creationPolicy: Owner}
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}
{{- end }}
