import { Bell, ChevronRight, ClipboardCheck, Heart, MapPin, PackageCheck, RotateCcw, UserRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAppAuth } from '@/contexts/AuthContext'
import { useOrders } from '@/hooks/useOrders'
import { useWishlistStore } from '@/stores/wishlistStore'
import { formatCurrency, formatDate } from '@/utils/format'

export default function BuyerOverviewPage() {
  const auth = useAppAuth()
  const orders = useOrders({ pageSize: 5 })
  const wishlistCount = useWishlistStore((state) => state.productIds.length)
  const recent = orders.data?.data ?? []
  return <div><div className="flex flex-col gap-4 border-b pb-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-gray-500">Xin chào,</p><h1 className="mt-1 text-2xl font-black">{auth.user?.name || auth.user?.username}</h1><p className="mt-1 text-sm text-gray-500">Quản lý đơn hàng và hoạt động mua sắm của bạn.</p></div><span className="flex h-14 w-14 items-center justify-center rounded-lg bg-primary-50 text-primary-600"><UserRound className="h-7 w-7" /></span></div><div className="grid gap-3 py-6 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={ClipboardCheck} label="Tổng đơn" value={String(orders.data?.totalItems ?? 0)} /><Stat icon={PackageCheck} label="Đang giao" value={String(recent.filter((order) => order.status === 'SHIPPED').length)} /><Stat icon={Heart} label="Yêu thích" value={String(wishlistCount)} /><Stat icon={RotateCcw} label="Yêu cầu đổi trả" value="0" /></div><section className="border-y py-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">Đơn hàng gần đây</h2><Link to="/orders" className="flex items-center gap-1 text-sm font-semibold text-primary-600">Xem tất cả <ChevronRight className="h-4 w-4" /></Link></div>{recent.length === 0 ? <div className="bg-gray-50 px-5 py-8 text-center text-sm text-gray-500">Bạn chưa có đơn hàng nào.</div> : <div className="divide-y border-y">{recent.map((order) => <Link key={order.id} to={`/orders/${order.id}`} className="flex flex-col gap-3 bg-white px-4 py-4 hover:bg-gray-50 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold">Đơn #{order.id.slice(0, 8)}</p><p className="mt-1 text-xs text-gray-500">{formatDate(order.createdAt)} · {order.items.length} sản phẩm</p></div><div className="flex items-center justify-between gap-5"><span className="rounded bg-primary-50 px-2 py-1 text-xs font-semibold text-primary-700">{order.status}</span><strong>{formatCurrency(order.totalAmount, order.currency)}</strong></div></Link>)}</div>}</section><section className="grid gap-3 py-6 sm:grid-cols-3"><QuickLink to="/buyer/notifications" icon={Bell} title="Thông báo" text="Cập nhật trạng thái đơn và ưu đãi" /><QuickLink to="/buyer/wishlist" icon={Heart} title="Danh sách yêu thích" text="Sản phẩm bạn đã lưu" /><QuickLink to="/buyer/addresses" icon={MapPin} title="Sổ địa chỉ" text="Quản lý nơi nhận hàng" /></section></div>
}

function Stat({ icon: Icon, label, value }: { icon: typeof Heart; label: string; value: string }) { return <div className="surface-card p-4"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">{label}</span><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary-50 text-primary-500"><Icon className="h-4 w-4" /></span></div><p className="mt-3 text-2xl font-extrabold">{value}</p></div> }
function QuickLink({ to, icon: Icon, title, text }: { to: string; icon: typeof Heart; title: string; text: string }) { return <Link to={to} className="focus-ring surface-card flex items-start gap-3 p-4 transition hover:-translate-y-0.5 hover:border-primary-200"><span className="flex h-9 w-9 flex-none items-center justify-center rounded-xl bg-mint/15 text-emerald"><Icon className="h-4 w-4" /></span><div><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div></Link> }
