apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.storeName }}
  labels:
    {{- include "integration.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.externalSecrets.vaultServer }}
      path: {{ .Values.externalSecrets.vaultPath }}
      version: {{ .Values.externalSecrets.vaultVersion }}
      auth:
        kubernetes:
          mountPath: {{ .Values.externalSecrets.authMountPath }}
          role: {{ .Values.externalSecrets.authRole }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccountName }}
            namespace: {{ .Values.namespaces.externalSecrets }}

