apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopping-integration
  namespace: cicd
spec:
  project: shopping-cart
  sources:
    - repoURL: https://github.com/wilddog64/shopping-integration.git
      targetRevision: HEAD
      path: helmchart
      helm:
        valueFiles: [$values/values/local/10-shopping-integration.yaml]
    - repoURL: https://github.com/wilddog64/config-secret-secure.git
      targetRevision: HEAD
      ref: values
  destination:
    name: ubuntu-k3s
    namespace: shopping-cart-data
  syncPolicy:
    syncOptions: [CreateNamespace=true]
