import { Heart, Menu, Search, ShoppingCart, UserRound, X } from 'lucide-react'
import { Link, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { KeyboardEvent, useMemo, useState } from 'react'
import { BuyerDemoProvider, useBuyerDemo } from './demoStore'
import { categories, products } from './fixtures'
import { AccountPage, CartPage, CatalogPage, CheckoutPage, DetailPage, HomePage, OrderDetailPage, OrdersPage, ShopPage, SuccessPage } from './ShopDemoPages'
import { EmptyState } from './ShopDemoComponents'
import { demoPath, normalizeVietnamese } from './utils'
import './shop-demo.css'

function Header() { const { cart, wishlist, profileName, storageWarning, reset }=useBuyerDemo(); const nav=useNavigate(); const location=useLocation(); const [value,setValue]=useState(new URLSearchParams(location.search).get('q')??''); const [open,setOpen]=useState(false); const [menu,setMenu]=useState(false); const suggestions=useMemo(()=>products.filter(p=>normalizeVietnamese(`${p.name} ${p.brand}`).includes(normalizeVietnamese(value))).slice(0,6),[value]); const submit=(event:KeyboardEvent<HTMLInputElement>|React.FormEvent)=>{event.preventDefault();if(value.trim())nav(demoPath(`/products?q=${encodeURIComponent(value.trim())}`));else nav(demoPath('/products'));setOpen(false)};
 return <><div className="shop-demo-bar">Bản trải nghiệm — dữ liệu và giao dịch mô phỏng <span>{storageWarning?'Thay đổi chỉ giữ trong phiên này.':'Không dùng API, auth hoặc thanh toán thật.'}</span></div><header className="shop-header"><div className="shop-header-main"><Link className="shop-logo" to={demoPath('/')}><i>SC</i><span>ShopCart</span></Link><form className="shop-search" onSubmit={submit}><Search size={20}/><input aria-label="Tìm sản phẩm" placeholder="Tìm sản phẩm bạn cần" value={value} onFocus={()=>setOpen(true)} onChange={event=>{setValue(event.target.value);setOpen(true)}} onKeyDown={event=>{if(event.key==='Escape')setOpen(false)}}/>{open&&<div className="shop-search-popover"><b>{value?'Gợi ý sản phẩm':'Tìm gần đây'}</b>{(value?suggestions:products.slice(0,5)).map(product=><Link key={product.id} to={demoPath(`/products/${product.id}`)} onClick={()=>setOpen(false)}><img src={product.gallery[0]} alt=""/><span>{product.name}<small>{new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(product.variants[0].price)}</small></span></Link>)}</div>}</form><nav className="shop-header-actions"><Link to={demoPath('/wishlist')} aria-label="Yêu thích"><Heart size={21}/><small>{wishlist.length||''}</small></Link><Link to={demoPath('/cart')} aria-label="Giỏ hàng"><ShoppingCart size={22}/><small>{cart.length||''}</small></Link><Link to={demoPath('/account')} aria-label="Tài khoản"><UserRound size={21}/><span>{profileName}</span></Link></nav><button className="shop-menu-button" onClick={()=>setMenu(!menu)} aria-label="Mở danh mục">{menu?<X/>:<Menu/>}</button></div><nav className={`shop-category-bar ${menu?'open':''}`} aria-label="Danh mục">{categories.map(([id,label])=><Link onClick={()=>setMenu(false)} key={id} to={demoPath(`/products?category=${id}`)}>{label}</Link>)}<Link className="shop-deal-link" to={demoPath('/products?deal=true')}>Deal hôm nay</Link></nav></header>{menu&&<div className="shop-mobile-menu">{categories.map(([id,label,icon])=><Link key={id} to={demoPath(`/products?category=${id}`)} onClick={()=>setMenu(false)}><span>{icon}</span>{label}</Link>)}</div>}<button className="shop-demo-tools" onClick={()=>{if(window.confirm('Đặt lại toàn bộ giỏ, đơn và dữ liệu demo trong trình duyệt?'))reset()}}>Công cụ demo: đặt lại</button></> }
function Footer(){return <footer className="shop-footer"><div><b>Hỗ trợ mua hàng</b><Link to={demoPath('/support')}>FAQ demo</Link><Link to={demoPath('/support')}>Gửi yêu cầu hỗ trợ</Link></div><div><b>Chính sách minh họa</b><Link to={demoPath('/support')}>Đổi trả mô phỏng</Link><Link to={demoPath('/support')}>Giao hàng mô phỏng</Link></div><div><b>Về ShopCart</b><span>Storefront Buyer UI độc lập, không nhận thanh toán thật.</span></div></footer>}
function Shell(){return <div className="shop-demo"><Header/><main className="shop-content"><Routes><Route index element={<HomePage/>}/><Route path="products" element={<CatalogPage/>}/><Route path="products/:id" element={<DetailPage/>}/><Route path="shops/:id" element={<ShopPage/>}/><Route path="cart" element={<CartPage/>}/><Route path="checkout" element={<CheckoutPage/>}/><Route path="orders/success/:id" element={<SuccessPage/>}/><Route path="orders" element={<OrdersPage/>}/><Route path="orders/:id" element={<OrderDetailPage/>}/><Route path="account" element={<AccountPage/>}/><Route path="account/addresses" element={<AccountPage section="addresses"/>}/><Route path="wishlist" element={<AccountPage section="wishlist"/>}/><Route path="notifications" element={<AccountPage section="notifications"/>}/><Route path="vouchers" element={<AccountPage section="vouchers"/>}/><Route path="support" element={<AccountPage section="support"/>}/><Route path="*" element={<EmptyState title="Không tìm thấy trang demo" body="Trang bạn cần không nằm trong storefront Buyer." href="/" action="Về trang chủ demo"/>}/></Routes></main><Footer/></div>}
export default function ShopDemoApp(){return <BuyerDemoProvider><Shell/></BuyerDemoProvider>}
