# syntax=docker/dockerfile:1
FROM busybox:1.37.0
ADD --checksum=sha256:bbf83c151b6400709e2f225bdd07a04f839d9d13b8b93464241333fd25d3e3ba https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.31.1/opentelemetry-javaagent.jar /agent/opentelemetry-javaagent.jar
RUN chmod 0444 /agent/opentelemetry-javaagent.jar
USER 1000:1000
ENTRYPOINT ["cp", "/agent/opentelemetry-javaagent.jar", "/otel/opentelemetry-javaagent.jar"]
