{{- if .Values.meshSecurity.enabled }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata: {name: default, namespace: {{ .Values.namespaces.apps }}}
spec:
  mtls: {mode: {{ .Values.meshSecurity.mode }}}
---
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata: {name: default, namespace: {{ .Values.namespaces.payment }}}
spec:
  mtls: {mode: {{ .Values.meshSecurity.mode }}}
{{- end }}
