apiVersion: v1
kind: Service
metadata: {name: {{ .Values.postgresql.marketplace.name }}, namespace: {{ .Values.namespaces.data }} }
spec:
  ports: [{name: postgresql, port: {{ .Values.postgresql.port }}, targetPort: postgresql}]
  selector: {app.kubernetes.io/name: postgresql, app.kubernetes.io/instance: marketplace}
