apiVersion: v1
kind: Service
metadata: {name: {{ .Values.rabbitmq.name }}-headless, namespace: {{ .Values.namespaces.data }}}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - {name: amqp, port: {{ .Values.rabbitmq.ports.amqp }}, targetPort: amqp}
    - {name: management, port: {{ .Values.rabbitmq.ports.management }}, targetPort: management}
    - {name: epmd, port: {{ .Values.rabbitmq.ports.epmd }}, targetPort: epmd}
    - {name: dist, port: {{ .Values.rabbitmq.ports.distribution }}, targetPort: dist}
    - {name: prometheus, port: {{ .Values.rabbitmq.ports.prometheus }}, targetPort: prometheus}
  selector: {app.kubernetes.io/name: rabbitmq}
---
apiVersion: v1
kind: Service
metadata: {name: {{ .Values.rabbitmq.name }}, namespace: {{ .Values.namespaces.data }}}
spec:
  type: ClusterIP
  ports: [{name: amqp, port: {{ .Values.rabbitmq.ports.amqp }}, targetPort: amqp}]
  selector: {app.kubernetes.io/name: rabbitmq}
---
apiVersion: v1
kind: Service
metadata: {name: {{ .Values.rabbitmq.name }}-management, namespace: {{ .Values.namespaces.data }}}
spec:
  type: ClusterIP
  ports: [{name: management, port: {{ .Values.rabbitmq.ports.management }}, targetPort: management}]
  selector: {app.kubernetes.io/name: rabbitmq}
