apiVersion: v1
kind: ConfigMap
metadata: {name: {{ .Values.postgresql.orders.name }}-init, namespace: {{ .Values.namespaces.data }}}
data:
  01-init.sql: |
    {{- .Values.postgresql.orders.initSql | nindent 4 }}

