apiVersion: v1
kind: ConfigMap
metadata: {name: {{ .Values.rabbitmq.name }}-config, namespace: {{ .Values.namespaces.data }}}
data:
  definitions.json: {{ .Values.rabbitmq.definitions | toJson | quote }}
  {{- range $key, $value := .Values.rabbitmq.config }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
